In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt


In [2]:
xor_table = np.array([[0, 0, 0],
                      [1, 0, 1],
                      [0, 1, 1],
                      [1, 1, 0]], dtype=np.float32)

x_train = xor_table[:, :2]  # Inputs: x1, x2
y_train = xor_table[:, 2:]  # Labels: y

In [3]:
def create_xor_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation='relu', input_shape=(2,)),  # Hidden layer
        tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer
    ])
    
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [4]:
model = create_xor_model()
model.fit(x_train, y_train, epochs=500, verbose=0)

C:\Users\GIGABYTE\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
y_pred = model.predict(x_train).round().astype(np.uint8)
print("Predicted XOR Truth Table:")
print(np.column_stack((xor_table[:, :2], y_pred)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
Predicted XOR Truth Table:
[[0. 0. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 1. 1.]]
